name: GitHub Actions Demo
run-name: ${{ github.actor }} is building the application ğŸ—ï¸
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Instaling dependencies â¬"
      - run: npm install
      - run: echo "Building applicatin ğŸ‘·"
      - run: npm run build
      - run: echo "Building is complete âœ…"
    